'use client';
import {useCallback,useEffect,useMemo,useReducer,useRef,useState} from 'react';
import {ViewerEngine} from './ViewerEngine';import {initialState,reducer} from '@/state/facility-store';import {FLOOR_LABELS,LAYERS,TECH_LAYERS} from '@/config/facility';import rawManifest from '@/config/model-manifest.json';import type {Manifest} from '@/types/facility';import {TooltipButton} from '@/components/ui/TooltipButton';import {Icon} from '@/components/ui/Icon';import {FacilityAssets,FacilityAssetDetail} from './FacilityAssets';
import {FACILITY_ASSETS,FACILITY_RUNTIME,DEMO_ASSETS,DEMO_MODE} from '@/data/facility-assets';
import {buildAssetRegistry,visibleAssets} from '@/lib/asset-registry';
const manifest=rawManifest as Manifest;
const assetRegistry=buildAssetRegistry([...FACILITY_ASSETS,...(DEMO_MODE?DEMO_ASSETS:[])],FACILITY_RUNTIME);
export default function DigitalTwin(){
 const host=useRef<HTMLDivElement>(null),tooltip=useRef<HTMLDivElement>(null),compass=useRef<HTMLDivElement>(null),engine=useRef<ViewerEngine|null>(null);const [state,dispatch]=useReducer(reducer,initialState);const [progress,setProgress]=useState(0),[ready,setReady]=useState(false),[error,setError]=useState<string|null>(null),[layers,setLayers]=useState(false),[navigate,setNavigate]=useState(false),[inspector,setInspector]=useState(false),[search,setSearch]=useState(''),[notice,setNotice]=useState(''),[fullscreen,setFullscreen]=useState(false);
 const entity=manifest.entities.find(e=>e.id===state.selectedEntity);
 const assetBuilding=state.selectedFloor?state.selectedBuilding:(manifest.entities.find(e=>e.id===state.activeCameraPreset&&e.type==='building')?.id||null);
 const activeAssets=useMemo(()=>visibleAssets(assetRegistry,{activeLayers:state.activeLayers,buildingId:assetBuilding,floorId:state.selectedFloor,demoMode:DEMO_MODE}),[state.activeLayers,assetBuilding,state.selectedFloor]);
 const selectedAsset=activeAssets.find(a=>a.id===state.selectedAsset);
 const projectAsset=useCallback((p:[number,number,number])=>engine.current?.project(p)||null,[]);
 useEffect(()=>{if(state.selectedAsset&&!selectedAsset)dispatch({type:'asset',id:null});},[state.selectedAsset,selectedAsset]);
 const assetDetail=selectedAsset?<FacilityAssetDetail asset={selectedAsset} runtime={assetRegistry.runtimeById.get(selectedAsset.id)} embedded={state.drawerOpen&&!!entity} onClose={()=>dispatch({type:'asset',id:null})}/>:null;
 const select=(id:string)=>{const e=manifest.entities.find(e=>e.id===id);if(!e)return;dispatch({type:'layer',id:e.type==='building'?'buildings':'site',visible:true});dispatch({type:'select',id,building:e.type==='building'});setNavigate(false);setLayers(false);};
 useEffect(()=>{let instance:ViewerEngine;try{instance=new ViewerEngine(host.current!,tooltip.current!,compass.current!,manifest,{progress:setProgress,ready:()=>setReady(true),error:message=>setError(message||'Unable to open the model'),hover:id=>dispatch({type:'hover',id}),select:id=>{const e=manifest.entities.find(x=>x.id===id)!;dispatch({type:'layer',id:e.type==='building'?'buildings':'site',visible:true});dispatch({type:'select',id,building:e.type==='building'});setNavigate(false);setLayers(false);}});engine.current=instance;}catch{setError('Unable to open the model');}
 return()=>{instance?.dispose();engine.current=null;};},[]);
 useEffect(()=>{engine.current?.apply(state);},[state,ready]);
 useEffect(()=>{if(!notice)return;const timer=setTimeout(()=>setNotice(''),3500);return()=>clearTimeout(timer);},[notice]);
 useEffect(()=>{const changed=()=>setFullscreen(!!document.fullscreenElement);document.addEventListener('fullscreenchange',changed);return()=>document.removeEventListener('fullscreenchange',changed);},[]);
 useEffect(()=>{if(process.env.NODE_ENV!=='development'||!ready)return;Object.assign(window,{facilityDebug:{state:()=>state,inspect:()=>engine.current?.inspect(),camera:()=>engine.current?.camera.position.toArray(),target:()=>engine.current?.controls.target.toArray(),root:()=>engine.current?.root?.matrix.toArray(),floors:()=>engine.current?.floorInfo(),assets:()=>({demoMode:DEMO_MODE,ids:[...assetRegistry.assetById.keys()],visible:activeAssets.map(a=>a.id)})}});return()=>{delete (window as unknown as Record<string,unknown>).facilityDebug;};},[state,ready,activeAssets]);
 const reset=()=>{dispatch({type:'reset'});setLayers(false);setNavigate(false);engine.current?.focus('overview');};
 const preset=(id:string)=>{dispatch({type:'preset',id});engine.current?.focus(id);setNavigate(false);};
 const restore=()=>{dispatch({type:'restore'});engine.current?.focus(state.selectedEntity||'office');};
 const toggleFullscreen=async()=>{try{if(document.fullscreenElement)await document.exitFullscreen();else await document.documentElement.requestFullscreen();}catch{setNotice('Fullscreen is unavailable in this browser.');}};
 const floorInfo=ready?engine.current?.floorInfo():undefined;const floor= floorInfo?.floors.find(f=>f.id===state.selectedFloor);
 const rows=inspector?engine.current?.inspect().filter(r=>JSON.stringify(r).toLowerCase().includes(search.toLowerCase()))||[]:[];
 return <main className={'twin '+(ready?'is-ready':'')} onKeyDown={e=>{if(e.key==='Escape'){setLayers(false);setNavigate(false);setInspector(false);dispatch({type:'close'});}}}><div className="scene" ref={host}/>
 <div className="interface">
 <header className="topbar glass"><div className="identity"><span className="identity-mark"><Icon name="isolate"/></span><div><h1>South Dagon Facility</h1><small>CONNECTED FACILITY</small></div></div><div className="context"><span/> {entity?.label||'Overview'}{state.selectedFloor&&<><b>/</b>{state.selectedFloor}</>}</div><div className="top-actions"><TooltipButton icon="reset" label="Reset View" onClick={reset}/><TooltipButton icon="sun" label={state.dayNightMode==='day'?'Night mode':'Day mode'} className={state.dayNightMode==='night'?'active':''} onClick={()=>dispatch({type:'night'})}/><TooltipButton icon="layers" label="Layers" aria-expanded={layers} onClick={()=>{setLayers(!layers);setNavigate(false);}}/><span className="divider"/><TooltipButton icon="fullscreen" label={fullscreen?'Exit fullscreen':'Fullscreen'} onClick={toggleFullscreen}/></div></header>
 <div className="navigation-anchor"><button className="nav-trigger glass" onClick={()=>{setNavigate(!navigate);setLayers(false);}} aria-expanded={navigate}><Icon name="menu"/><span>Explore facility</span><Icon name="chevron"/></button>{navigate&&<nav className="nav-menu glass" aria-label="Facility navigation"><span className="eyebrow">SPACES</span>{manifest.entities.filter(e=>e.sourceKeys.length).map(e=><button key={e.id} data-entity={e.id} onClick={()=>select(e.id)}><Icon name={e.type==='building'?'building':'focus'}/>{e.label}<Icon name="chevron"/></button>)}</nav>}</div>
 {layers&&<aside className="layers-panel glass"><div className="panel-title"><h2>Spatial layers</h2><TooltipButton icon="close" label="Close layers" onClick={()=>setLayers(false)}/></div><span className="eyebrow">BUILT ENVIRONMENT</span>{LAYERS.map(l=><label key={l.id}><input type="checkbox" data-layer={l.id} checked={state.activeLayers[l.id]} onChange={e=>dispatch({type:'layer',id:l.id,visible:e.target.checked})}/><span>{l.label}</span></label>)}<span className="eyebrow future-label">CONNECTED SYSTEMS <small>V2</small></span>{TECH_LAYERS.map(l=><label key={l.id} ><input type="checkbox" data-layer={l.id} checked={!!state.activeLayers[l.id]} onChange={e=>dispatch({type:'layer',id:l.id,visible:e.target.checked})}/><span>{l.label}</span><small>{(assetRegistry.assetsByLayer.get(l.id)||[]).filter(a=>a.enabled!==false&&!a.demo).length} assets{DEMO_MODE&&<> · {(assetRegistry.assetsByLayer.get(l.id)||[]).filter(a=>a.demo).length} demo</>}</small></label>)}</aside>}
 {state.drawerOpen&&entity&&<aside className="detail-drawer glass" aria-label="Selected space"><div className="drawer-grip"/><div className="panel-title"><span className="eyebrow">SELECTED SPACE</span><TooltipButton icon="close" label="Close details" onClick={()=>dispatch({type:'close'})}/></div><div className="entity-heading"><span className="entity-icon"><Icon name={entity.type==='building'?'building':'focus'}/></span><div><h2>{entity.label}</h2><p>{entity.subtitle}</p></div></div><div className="model-badge"><i/>Final model <span>·</span> Spatial view</div><div className="drawer-actions"><button onClick={()=>engine.current?.focus(entity.id)}><Icon name="focus"/>Focus</button><button className={state.isolated?'active':''} onClick={()=>dispatch({type:'isolate'})}><Icon name="isolate"/>{state.isolated?'In context':'Isolate'}</button></div>
 {entity.id==='office'&&<section className="floor-explorer"><div className="floor-title"><Icon name="floor"/><h3>Floor Explorer</h3><span>07</span></div><div className="floor-rail">{FLOOR_LABELS.map(f=><button key={f} disabled={!floorInfo?.floors.some(level=>level.id===f)} title={(f==='G1'?'Ground Level I':f==='G2'?'Ground Level II':f)+' · '+(f==='G1'||f==='G2'?'Limited Mapping':'Partial Cutaway')} data-floor={f} aria-pressed={state.selectedFloor===f} className={state.selectedFloor===f?'active':''} onClick={()=>dispatch({type:'floor',id:f})}>{f}</button>)}</div>{state.selectedFloor?<div className="floor-context"><span>{state.selectedFloor} selected</span><p role="status">{floor?.limited?'Limited Mapping':'Partial Cutaway'}</p></div>:<p className="floor-hint">Explore Floor</p>}{floorInfo?.error&&<p className="floor-hint" role="alert">{floorInfo.error}</p>}</section>}
 {assetDetail}<button className="restore-button" onClick={restore}><Icon name="reset"/>Restore Building</button></aside>}
 <div className="bottom-bar"><div className="status-strip glass"><i/><span>Model loaded</span><b>·</b><span>{state.selectedFloor?state.selectedFloor:state.activeCameraPreset==='overview'?'Overview':'Spatial view'}</span><b>·</b><span>{Object.values(state.activeLayers).filter(Boolean).length} layers</span></div><nav className="presets glass" aria-label="Camera presets">{[{id:'overview',label:'Overview'},{id:'front',label:'Front'},{id:'office',label:'Office'},{id:'warehouse',label:'Warehouse'}].map(p=><button key={p.id} data-preset={p.id} className={state.activeCameraPreset===p.id?'active':''} onClick={()=>preset(p.id)}>{p.label}</button>)}<select aria-label="More camera presets" value="" onChange={e=>preset(e.target.value)}><option value="" disabled>More ↗</option><option value="aerial">Aerial</option>{manifest.entities.filter(e=>e.type==='area').map(e=><option key={e.id} value={e.id}>{e.label}</option>)}</select></nav><div className="orientation glass" title="Model axes. Survey north is not established."><small>−Z</small><div ref={compass}><Icon name="compass"/></div><span>MODEL</span></div></div>
 <div className="gesture-hint">Drag to orbit <span>·</span> Scroll to zoom <span>·</span> Right-drag to pan</div>
 {process.env.NODE_ENV==='development'&&<button className="dev-trigger" title="Development scene inspector" onClick={()=>setInspector(true)}><Icon name="inspect"/></button>}
 </div>
 <div className="world-tooltip glass" ref={tooltip} hidden><Icon name="building"/><div><strong/><small/></div></div>
 {notice&&<div className="toast glass" role="status">{notice}</div>}
 {!ready||error?<div className="loading-screen"><div className="loading-brand"><Icon name="isolate"/></div><span className="eyebrow">SOUTH DAGON FACILITY</span><h2>{error||'Loading Digital Twin'}</h2>{error?<><p>Please check the connection and try again.</p><button onClick={()=>location.reload()}>Try again</button></>:<><div className="progress-track"><div style={{width:progress+'%'}}/></div><span className="progress-value">{Math.round(progress)}%</span></>}</div>:null}
 {process.env.NODE_ENV==='development'&&inspector&&<div className="inspector-backdrop"><section className="inspector glass" role="dialog" aria-label="Development scene inspector"><div className="panel-title"><h2>Scene registry</h2><TooltipButton icon="close" label="Close inspector" onClick={()=>setInspector(false)}/></div><p>DEVELOPMENT ONLY · {manifest.meshNodes} assets · Native glTF Y-up</p><input aria-label="Search scene registry" value={search} onChange={e=>setSearch(e.target.value)} placeholder="Node, source object, group or key"/><small>{rows.length} matches; first 60 shown</small><div className="inspector-rows">{rows.slice(0,60).map(r=><pre key={r.id}>{JSON.stringify(r,null,2)}</pre>)}</div></section></div>}
 {ready&&<FacilityAssets items={activeAssets} registry={assetRegistry} selected={state.selectedAsset} onSelect={id=>dispatch({type:'asset',id})} project={projectAsset}/>}
 {(!state.drawerOpen||!entity)&&assetDetail}
 {DEMO_MODE&&<div className="demo-banner">DEMO · Synthetic asset locations</div>}
 </main>;
}
